### PR TITLE
Bumped bbl version to 8.4.74

### PR DESCRIPTION
**Pull request by jaristiz**
Authored-by: Jhonathan Aristizabal <jhonathana@vmware.com>

### CODE REVIEW

**Review by davewalter — APPROVED** [review]
LGTM!

**Comment by mephmanx** [comment]
Any update on this?

**Comment by jaristiz** [comment]
We already got a new bbl version with a fix on UAA, should I cancel this one and create a new PR?

**Comment by mephmanx** [comment]
Can we get bbl version updated!!!

**Comment by davewalter** [comment]
We should probably just bump to `v8.4.77` at this point.

**Comment by mephmanx** [comment]
Can we get it bumped!!!  we have been waiting a bit...

**Comment by jaristiz** [comment]
Bumped again to v8.4.77 so we get the latest version on merge.

**Comment by mephmanx** [comment]
We still have not yet got this merged....

**Comment by mephmanx** [comment]
Can we get this merged!!

**Pull request merged**
