### PR TITLE
Update formulas to work with linux machines

### PR DESCRIPTION
**Pull request by vlad-stoian**
People using linuxbrew (linux version of homebrew, http://linuxbrew.sh/) that are using this tap will get the mac os binaries, which will not work. I've updated the formulas to make them work with linux as well.

I see some automatic commits on this repos, so I'm a little afraid that these will get reverted on the next automatic commit. Who should I talk to about that ?

### CODE REVIEW

**Comment by markstokan** [comment]
Normally we pass these stories off to the owners of the individual tool distributed via brew.
Since this change applies across the board, we'll merge it in ourselves.

**Comment by voelzmo** [comment]
The original concern that this change gets overridden on the next commit by CI is still valid, though, right? Do you talk to the individual teams to ensure this makes it into their CIs, Mark?

On 6. Oct 2017, at 02:45, Mark Stokan <notifications@github.com<mailto:notifications@github.com>> wrote:


Normally we pass these stories off to the owners of the individual tool distributed via brew.
Since this change applies across the board, we'll merge it in ourselves.

**Comment by markstokan** [comment]
Ah.

Marco I'm not familiar with "the original concern" you speak of.  It sounds as though there was a previous discussion on the best way to integrate this pull request that I wasn't party to.

Extrapolating, it seems you're suggesting that each team responsible for a tool distributed through the homebrew-tap repo needs to incorporate these changes into there CI.  

I can begin reaching out to these teams and see how they'd like to proceed.

If you have any additional context from earlier discussions, perhaps you could share them here.

**Comment by markstokan** [comment]
I have reverted the merge.

Sorry for the run-around, Vlad.  It sounds like the best course of action would be to re-submit these changes as a series of pull requests, one for each tool.  

Each team will be sent a single pull request to integrate these changes into the CI for their particular tool

**Comment by voelzmo** [comment]
@markstokan I called this comment from @vlad-stoian "the original concern" in lack of a better word:
> I see some automatic commits on this repos, so I'm a little afraid that these will get reverted on the next automatic commit. Who should I talk to about that ?

Sorry for the confusion :) I guess the approach of sending PRs to the individual teams makes sense. Thanks!

**Comment by XenoPhex** [comment]
FYI: The CF CLI team just added support for Linux-brew to the CF CLI formula.

**Comment by evanfarrar** [comment]
I will add support for linuxbrew to the bbl backlog

**Pull request merged**
