### PR TITLE
Update bosh-cli version

### PR DESCRIPTION
**Pull request by APShirley**

### CODE REVIEW

**Comment by sslavic** [comment]
@APShirley please consider updating the pull request to latest bosh-cli release available (see [here](https://main.bosh-ci.cf-app.com/teams/main/pipelines/bosh:cli/resources/release-bucket-darwin)). Also please change in description "alpha" --> "beta".

**Comment by cppforlife** [comment]
@wendorf is doing a PR to make this automated.

**Comment by sslavic** [comment]
Thanks @cppforlife and @wendorf !

Noticed that README needs to be updated. Package for bosh 2 cli is `bosh-cli` instead of `bosh-cli-alpha`

**Comment by wendorf** [comment]
@sslavic Thanks for the heads-up. I filed #26 to address that.

**Pull request closed without merging**
