### PR TITLE
linuxbrew compatibility

### PR DESCRIPTION
**Pull request by tannevaled**
do not merge bbl.rb, only bosh-cli.rb

### CODE REVIEW

**Comment by mxplusb** [comment]
Is this still open or should it be retried?

**Comment by tannevaled** [comment]
only the mac part already exist, not the linux one.

**Comment by ipolyzos** [comment]
I have issued a new PR for the same issue and bosh-cli version 6.2.1, if you could please check it

**Comment by aashah** [comment]
Closing this PR. The bosh-cli formula is managed via Concourse and our publishing flow, and gets overwritten by the tooling there. This should be fixed via https://github.com/cloudfoundry/bosh-cli/commit/3d10b621ff97ae8b16d1862a27b5de06d240e09e, and future formulas should have a linux compatible binary.

-- Aakash && @krutten

**Pull request closed without merging**
